// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice = never;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Excerpt field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type FooterMultiColumnDocumentDataSlicesSlice = FooterLinkBlockSlice;

type FooterMultiColumnDocumentDataSlices1Slice = FooterLinkBlockSlice;

type FooterMultiColumnDocumentDataSlices2Slice = FooterLinkBlockSlice;

/**
 * Content for Footer Multi Column documents
 */
interface FooterMultiColumnDocumentData {
  /**
   * Slice Zone field in *Footer Multi Column*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_multi_column.slices[]
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterMultiColumnDocumentDataSlicesSlice> /**
   * Slice Zone field in *Footer Multi Column*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_multi_column.slices1[]
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<FooterMultiColumnDocumentDataSlices1Slice> /**
   * Slice Zone field in *Footer Multi Column*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_multi_column.slices2[]
   * - **Tab**: Column 3
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<FooterMultiColumnDocumentDataSlices2Slice>;
}

/**
 * Footer Multi Column document from Prismic
 *
 * - **API ID**: `footer_multi_column`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterMultiColumnDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FooterMultiColumnDocumentData>,
    "footer_multi_column",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | FaqSlice
  | ProcessSlice
  | TestimonialSlice
  | ImageWithTextSlice
  | FeaturesSlice
  | HeroSlice
  | RichTextSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Homepage Title
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Layout → Navigation*
 */
export interface LayoutDocumentDataNavigationItem {
  /**
   * Label field in *Layout → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Layout → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Layout → Social Media*
 */
export interface LayoutDocumentDataSocialMediaItem {
  /**
   * Platform field in *Layout → Social Media*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_media[].platform
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  platform: prismic.SelectField<
    "Facebook" | "Instagram" | "LinkedIn" | "TikTok" | "YouTube"
  >;

  /**
   * Label field in *Layout → Social Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_media[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Layout → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type LayoutDocumentDataSlices1Slice =
  | FooterMultiColumnSlice
  | FooterHeadingSlice;

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * CTA Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta_link
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Logo field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.logo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.navigation[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<LayoutDocumentDataNavigationItem>> /**
   * Privacy Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.privacy_label
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  privacy_label: prismic.KeyTextField;

  /**
   * Privacy Link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.privacy_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_link: prismic.LinkField;

  /**
   * Copyright field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.copyright
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * Social Media field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_media[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<Simplify<LayoutDocumentDataSocialMediaItem>>;

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<LayoutDocumentDataSlices1Slice>;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * TItle field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Domain field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.domain
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  domain: prismic.KeyTextField;

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Site Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_meta_description: prismic.KeyTextField;

  /**
   * Site Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_meta_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogPostDocument
  | FooterMultiColumnDocument
  | HomepageDocument
  | LayoutDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Heading field in *Faq → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Question field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Heading field in *Features → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter section heading
   * - **API ID Path**: features.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter short section description
   * - **API ID Path**: features.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceDefaultItem {
  /**
   * Feature Heading field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter feature heading
   * - **API ID Path**: features.items[].feature_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_heading: prismic.RichTextField;

  /**
   * Feature Description field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter short feature description
   * - **API ID Path**: features.items[].feature_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_description: prismic.RichTextField;

  /**
   * Button Label field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Features → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceSecondaryPrimary {
  /**
   * Heading field in *Features → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter section heading
   * - **API ID Path**: features.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter short section description
   * - **API ID Path**: features.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceSecondaryItem {
  /**
   * Feature Heading field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter feature heading
   * - **API ID Path**: features.items[].feature_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_heading: prismic.RichTextField;

  /**
   * Feature Description field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter short feature description
   * - **API ID Path**: features.items[].feature_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_description: prismic.RichTextField;

  /**
   * Button Label field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Features → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Secondary variation for Features Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<FeaturesSliceSecondaryPrimary>,
  Simplify<FeaturesSliceSecondaryItem>
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSlicePrimaryPrimary {
  /**
   * Heading field in *Features → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter section heading
   * - **API ID Path**: features.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter short section description
   * - **API ID Path**: features.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSlicePrimaryItem {
  /**
   * Feature Heading field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter feature heading
   * - **API ID Path**: features.items[].feature_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_heading: prismic.RichTextField;

  /**
   * Feature Description field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter short feature description
   * - **API ID Path**: features.items[].feature_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_description: prismic.RichTextField;

  /**
   * Button Label field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Features → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary variation for Features Slice
 *
 * - **API ID**: `primary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlicePrimary = prismic.SharedSliceVariation<
  "primary",
  Simplify<FeaturesSlicePrimaryPrimary>,
  Simplify<FeaturesSlicePrimaryItem>
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation =
  | FeaturesSliceDefault
  | FeaturesSliceSecondary
  | FeaturesSlicePrimary;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *FooterHeading → Primary*
 */
export interface FooterHeadingSliceDefaultPrimary {
  /**
   * Heading field in *FooterHeading → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Default variation for FooterHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterHeading*
 */
type FooterHeadingSliceVariation = FooterHeadingSliceDefault;

/**
 * FooterHeading Shared Slice
 *
 * - **API ID**: `footer_heading`
 * - **Description**: FooterHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterHeadingSlice = prismic.SharedSlice<
  "footer_heading",
  FooterHeadingSliceVariation
>;

/**
 * Primary content in *FooterLinkBlock → Primary*
 */
export interface FooterLinkBlockSliceDefaultPrimary {
  /**
   * Block Title field in *FooterLinkBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_link_block.primary.block_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  block_title: prismic.KeyTextField;
}

/**
 * Primary content in *FooterLinkBlock → Items*
 */
export interface FooterLinkBlockSliceDefaultItem {
  /**
   * Label field in *FooterLinkBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_link_block.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *FooterLinkBlock → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_link_block.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for FooterLinkBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinkBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterLinkBlockSliceDefaultPrimary>,
  Simplify<FooterLinkBlockSliceDefaultItem>
>;

/**
 * Slice variation for *FooterLinkBlock*
 */
type FooterLinkBlockSliceVariation = FooterLinkBlockSliceDefault;

/**
 * FooterLinkBlock Shared Slice
 *
 * - **API ID**: `footer_link_block`
 * - **Description**: FooterLinkBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinkBlockSlice = prismic.SharedSlice<
  "footer_link_block",
  FooterLinkBlockSliceVariation
>;

/**
 * Primary content in *FooterMultiColumn → Primary*
 */
export interface FooterMultiColumnSliceDefaultPrimary {
  /**
   * Heading field in *FooterMultiColumn → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_multi_column.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Layout field in *FooterMultiColumn → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_multi_column.primary.layout
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  layout: prismic.ContentRelationshipField<"footer_multi_column">;
}

/**
 * Default variation for FooterMultiColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMultiColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterMultiColumnSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterMultiColumn*
 */
type FooterMultiColumnSliceVariation = FooterMultiColumnSliceDefault;

/**
 * FooterMultiColumn Shared Slice
 *
 * - **API ID**: `footer_multi_column`
 * - **Description**: FooterMultiColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMultiColumnSlice = prismic.SharedSlice<
  "footer_multi_column",
  FooterMultiColumnSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Benefit driven headline
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short: What, Who, How
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Style field in *Hero → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Style of button
   * - **Default Value**: default
   * - **API ID Path**: hero.primary.button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    "default" | "secondary" | "outline" | "ghost" | "destructive" | "link",
    "filled"
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceWithImagePrimary {
  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Benefit driven headline
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short: What, Who, How
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Style field in *Hero → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Style of button
   * - **Default Value**: default
   * - **API ID Path**: hero.primary.button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    "default" | "secondary" | "outline" | "ghost" | "destructive" | "link",
    "filled"
  >;
}

/**
 * With Image variation for Hero Slice
 *
 * - **API ID**: `withImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithImage = prismic.SharedSliceVariation<
  "withImage",
  Simplify<HeroSliceWithImagePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithImage;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Text field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your text here
   * - **API ID Path**: image_with_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceRightImagePrimary {
  /**
   * Text field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your text here
   * - **API ID Path**: image_with_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Right Image variation for ImageWithText Slice
 *
 * - **API ID**: `rightImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceRightImage = prismic.SharedSliceVariation<
  "rightImage",
  Simplify<ImageWithTextSliceRightImagePrimary>,
  never
>;

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation =
  | ImageWithTextSliceDefault
  | ImageWithTextSliceRightImage;

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  "image_with_text",
  ImageWithTextSliceVariation
>;

/**
 * Primary content in *Process → Primary*
 */
export interface ProcessSliceDefaultPrimary {
  /**
   * Title field in *Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optionally add a section title
   * - **API ID Path**: process.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Heading field in *Process → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter process heading
   * - **API ID Path**: process.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Process → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optionally describe the process
   * - **API ID Path**: process.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Process → Items*
 */
export interface ProcessSliceDefaultItem {
  /**
   * Icon field in *Process → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Optionally select an icon
   * - **API ID Path**: process.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"message" | "call" | "people">;

  /**
   * Step Title field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.items[].step_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_title: prismic.KeyTextField;

  /**
   * description field in *Process → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe this step
   * - **API ID Path**: process.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optionally add a button
   * - **API ID Path**: process.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Process → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add a link
   * - **API ID Path**: process.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessSliceDefaultPrimary>,
  Simplify<ProcessSliceDefaultItem>
>;

/**
 * Slice variation for *Process*
 */
type ProcessSliceVariation = ProcessSliceDefault;

/**
 * Process Shared Slice
 *
 * - **API ID**: `process`
 * - **Description**: Process
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessSlice = prismic.SharedSlice<
  "process",
  ProcessSliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Rich Text field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Rich Text Content
   * - **API ID Path**: rich_text.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceSecondaryPrimary {
  /**
   * Rich Text field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Rich Text Content
   * - **API ID Path**: rich_text.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField;
}

/**
 * Secondary variation for RichText Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<RichTextSliceSecondaryPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault | RichTextSliceSecondary;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *Testimonial → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Quote field in *Testimonial → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter quote here
   * - **API ID Path**: testimonial.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Name field in *Testimonial → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter quote author
   * - **API ID Path**: testimonial.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      FooterMultiColumnDocument,
      FooterMultiColumnDocumentData,
      FooterMultiColumnDocumentDataSlicesSlice,
      FooterMultiColumnDocumentDataSlices1Slice,
      FooterMultiColumnDocumentDataSlices2Slice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataNavigationItem,
      LayoutDocumentDataSocialMediaItem,
      LayoutDocumentDataSlices1Slice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceDefaultItem,
      FeaturesSliceSecondaryPrimary,
      FeaturesSliceSecondaryItem,
      FeaturesSlicePrimaryPrimary,
      FeaturesSlicePrimaryItem,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      FeaturesSliceSecondary,
      FeaturesSlicePrimary,
      FooterHeadingSlice,
      FooterHeadingSliceDefaultPrimary,
      FooterHeadingSliceVariation,
      FooterHeadingSliceDefault,
      FooterLinkBlockSlice,
      FooterLinkBlockSliceDefaultPrimary,
      FooterLinkBlockSliceDefaultItem,
      FooterLinkBlockSliceVariation,
      FooterLinkBlockSliceDefault,
      FooterMultiColumnSlice,
      FooterMultiColumnSliceDefaultPrimary,
      FooterMultiColumnSliceVariation,
      FooterMultiColumnSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceWithImagePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithImage,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceRightImagePrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      ImageWithTextSliceRightImage,
      ProcessSlice,
      ProcessSliceDefaultPrimary,
      ProcessSliceDefaultItem,
      ProcessSliceVariation,
      ProcessSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceSecondaryPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      RichTextSliceSecondary,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
    };
  }
}
