// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  footer_heading: dynamic(() => import("./FooterHeading")),
  footer_link_block: dynamic(() => import("./FooterLinkBlock")),
  footer_multi_column: dynamic(() => import("./FooterMultiColumn")),
  hero: dynamic(() => import("./Hero")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  rich_text: dynamic(() => import("./RichText")),
  testimonial: dynamic(() => import("./Testimonial")),
};
